CREATE TABLE Users (
    id INT PRIMARY KEY IDENTITY(1,1),
    username NVARCHAR(50) UNIQUE NOT NULL,
    password_hash NVARCHAR(255) NOT NULL,
    email NVARCHAR(100) UNIQUE NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),
    updated_at DATETIME DEFAULT GETDATE()
);

CREATE TABLE Roles (
    id INT PRIMARY KEY IDENTITY(1,1),
    role_name NVARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE UserRoles (
    id INT PRIMARY KEY IDENTITY(1,1),
    user_id INT FOREIGN KEY REFERENCES Users(id) ON DELETE CASCADE,
    role_id INT FOREIGN KEY REFERENCES Roles(id) ON DELETE CASCADE
);

CREATE TABLE Permissions (
    id INT PRIMARY KEY IDENTITY(1,1),
    permission_key NVARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE RolePermissions (
    id INT PRIMARY KEY IDENTITY(1,1),
    role_id INT FOREIGN KEY REFERENCES Roles(id) ON DELETE CASCADE,
    permission_id INT FOREIGN KEY REFERENCES Permissions(id) ON DELETE CASCADE
);
